version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - kind/DEPENDENCIES
      - status/CR-NEEDED
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

