name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
      - uses: actions/checkout@v5
      - name: Install packages
        run: pacman -Syu rust gcc openssl clang pkgconf --noconfirm --needed
      - name: Run the checks
        run: cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo build && cargo test
